# Generated by Django 2.2.19 on 2021-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whole', '0003_auto_20210411_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(default=' ', help_text='search for articles based on title/content', max_length=30),
        ),
    ]
