# Generated by Django 2.2.19 on 2021-04-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assimilate', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
