# Generated by Django 2.2.19 on 2021-04-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assimilate', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='domain',
            field=models.CharField(help_text='Enter the domain.', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Enter your account display name.', max_length=30),
        ),
    ]
