# Generated by Django 2.2.19 on 2021-04-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assimilate', '0007_auto_20210409_0234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
