# Generated by Django 2.2.19 on 2021-04-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assimilate', '0009_auto_20210411_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
