# Generated by Django 2.2.19 on 2021-04-17 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assimilate', '0010_auto_20210411_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assimilate_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EditLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_title', models.CharField(max_length=200)),
                ('new_title', models.CharField(max_length=200)),
                ('old_content', models.TextField()),
                ('new_content', models.TextField()),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assimilate_editlogs_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
